"""add ingestion data foundation

Revision ID: 3944daf20671
Revises: 20260809_0001
Create Date: 2026-08-14 12:29:37.225326
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3944daf20671"
down_revision: str | None = "20260809_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bbox_prefix = "bbox_" if op.get_bind().dialect.name == "postgresql" else ""
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("dataset_type", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=True),
        sa.Column("split", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "BLOCKED_CREDENTIALS",
                "CANCELLED",
                name="ingestionjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("source_manifest", sa.JSON(), nullable=False),
        sa.Column("target_bucket", sa.String(length=255), nullable=False),
        sa.Column("target_prefix", sa.String(length=1024), nullable=False),
        sa.Column("error_message", sa.String(length=4096), nullable=True),
        sa.Column("result_metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_request_fingerprint"), "ingestion_jobs", ["request_fingerprint"], unique=True
    )
    op.create_table(
        "qa_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_image_id", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("object_url", sa.String(length=2048), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_images")),
        sa.UniqueConstraint("filename", name=op.f("uq_qa_images_filename")),
    )
    op.create_index(op.f("ix_qa_images_source_image_id"), "qa_images", ["source_image_id"], unique=True)
    op.create_table(
        "ingestion_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_uri", sa.String(length=2048), nullable=True),
        sa.Column("object_key", sa.String(length=2048), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingestion_jobs.id"], name=op.f("fk_ingestion_assets_job_id_ingestion_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_assets")),
        sa.UniqueConstraint("job_id", "object_key", name="uq_ingestion_asset_job_key"),
    )
    op.create_index(op.f("ix_ingestion_assets_job_id"), "ingestion_assets", ["job_id"], unique=False)
    op.create_table(
        "ingestion_job_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "REQUESTED", "RESOLVE_SOURCE", "ACQUIRE_RAW", "ADAPT", "PERSIST", "FINALIZE", name="ingestionphase"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "BLOCKED_CREDENTIALS",
                "CANCELLED",
                name="ingestionjobstatus",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=2048), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["ingestion_jobs.id"], name=op.f("fk_ingestion_job_events_job_id_ingestion_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_job_events")),
    )
    op.create_index(op.f("ix_ingestion_job_events_job_id"), "ingestion_job_events", ["job_id"], unique=False)
    op.create_table(
        "qa_objects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("source_object_key", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(f"{bbox_prefix}xmin", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}ymin", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}xmax", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}ymax", sa.Float(), nullable=False),
        sa.Column(
            "review_status", sa.Enum("VERIFIED", "NEEDS_REVIEW", "UNMATCHED", name="qareviewstatus"), nullable=False
        ),
        sa.Column("calibration", sa.JSON(), nullable=False),
        sa.Column("cuboid_corners", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["image_id"], ["qa_images.id"], name=op.f("fk_qa_objects_image_id_qa_images")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_objects")),
        sa.UniqueConstraint("image_id", "source_object_key", name="uq_qa_object_image_source_key"),
    )
    op.create_index(op.f("ix_qa_objects_image_id"), "qa_objects", ["image_id"], unique=False)
    op.create_table(
        "qa_object_provenance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qa_object_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Enum("COCO", "CVAT", "KITTI", "NUSCENES", name="annotationsource"), nullable=False),
        sa.Column("source_annotation_id", sa.String(length=255), nullable=False),
        sa.Column(f"{bbox_prefix}xmin", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}ymin", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}xmax", sa.Float(), nullable=False),
        sa.Column(f"{bbox_prefix}ymax", sa.Float(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qa_object_id"], ["qa_objects.id"], name=op.f("fk_qa_object_provenance_qa_object_id_qa_objects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_object_provenance")),
        sa.UniqueConstraint("qa_object_id", "source", "source_annotation_id", name="uq_qa_provenance"),
    )
    op.create_index(
        op.f("ix_qa_object_provenance_qa_object_id"), "qa_object_provenance", ["qa_object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qa_object_provenance_qa_object_id"), table_name="qa_object_provenance")
    op.drop_table("qa_object_provenance")
    op.drop_index(op.f("ix_qa_objects_image_id"), table_name="qa_objects")
    op.drop_table("qa_objects")
    op.drop_index(op.f("ix_ingestion_job_events_job_id"), table_name="ingestion_job_events")
    op.drop_table("ingestion_job_events")
    op.drop_index(op.f("ix_ingestion_assets_job_id"), table_name="ingestion_assets")
    op.drop_table("ingestion_assets")
    op.drop_index(op.f("ix_qa_images_source_image_id"), table_name="qa_images")
    op.drop_table("qa_images")
    op.drop_index(op.f("ix_ingestion_jobs_request_fingerprint"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ("annotationsource", "qareviewstatus", "ingestionphase", "ingestionjobstatus"):
            postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
